services:
  jira:
    image: atlassian/jira-software:10.3
    container_name: jira
    ports:
      - 8080:8080
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS=-Datlassian.plugins.enable.wait=300
    volumes:
      - ./Atlassian.Jira.Test.Integration.Setup/import/:/var/atlassian/application-data/jira/import/
  db:
    image: postgres:18.0
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Password1!
      - POSTGRES_USER=jiraUser
      - POSTGRES_DB=jira
  adminer:
    image: adminer:5.4.0
    container_name: adminer
    ports:
      - 8081:8080
