namespace Atlassian.Jira.OAuth;

/// <summary>
/// Request token information returned by Jira.
/// </summary>
public class OAuthRequestToken
{
    /// <summary>
    /// The url to authorize the request token generated by Jira.
    /// </summary>
    public readonly string AuthorizeUri;

    /// <summary>
    /// The OAuth request token generated by Jira.
    /// </summary>
    public readonly string OAuthToken;

    /// <summary>
    /// The OAuth token secret generated by Jira.
    /// </summary>
    public readonly string OAuthTokenSecret;

    /// <summary>
    /// Confirmation from Jira that it received the OAuth callback url.
    /// </summary>
    public readonly string OAuthCallbackConfirmation;

    /// <summary>
    /// Creates a request token containing the response from Jira.
    /// </summary>
    /// <param name="authorizeUri">The url to authorize the request token generated by Jira.</param>
    /// <param name="oAuthToken">The OAuth request token generated by Jira.</param>
    /// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
    /// <param name="oAuthCallbackConfirmation"></param>
    public OAuthRequestToken(
        string authorizeUri,
        string oAuthToken,
        string oAuthTokenSecret,
        string oAuthCallbackConfirmation)
    {
        AuthorizeUri = authorizeUri;
        OAuthToken = oAuthToken;
        OAuthTokenSecret = oAuthTokenSecret;
        OAuthCallbackConfirmation = oAuthCallbackConfirmation;
    }
}
